server:
  port: 7077


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.181.141:3306/linsir_play?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: yu@2023

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl