server:
  port: 7075


spring:
  datasource:
    url: jdbc:mysql://106.55.181.141:3306/linsir_saas?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&&serverTimezone=Asia/Shanghai
    username: root
    password: yu@2023
  application:
    name: db-core